APP_ENVIRONMENT: "local"
SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/dropcar"
SPRING_DATASOURCE_DATABASE: "dropcar"
SPRING_DATASOURCE_HOSTNAME: "localhost"
SPRING_DATASOURCE_USERNAME: "postgres"
SPRING_DATASOURCE_PASSWORD: "postgres"
